/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppPatientsIndexRouteImport } from './routes/_app/patients.index'
import { Route as AppVisitsNewRouteImport } from './routes/_app/visits.new'
import { Route as AppPatientsNewRouteImport } from './routes/_app/patients.new'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app/patients.$patientId'
import { Route as AppVisitsVisitIdIndexRouteImport } from './routes/_app/visits.$visitId.index'
import { Route as AppVisitsVisitIdTriageRouteImport } from './routes/_app/visits.$visitId.triage'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsNewRoute = AppVisitsNewRouteImport.update({
  id: '/visits/new',
  path: '/visits/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsNewRoute = AppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsVisitIdIndexRoute = AppVisitsVisitIdIndexRouteImport.update({
  id: '/visits/$visitId/',
  path: '/visits/$visitId/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsVisitIdTriageRoute = AppVisitsVisitIdTriageRouteImport.update({
  id: '/visits/$visitId/triage',
  path: '/visits/$visitId/triage',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/visits/new': typeof AppVisitsNewRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/visits/$visitId/triage': typeof AppVisitsVisitIdTriageRoute
  '/visits/$visitId/': typeof AppVisitsVisitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/patients/new': typeof AppPatientsNewRoute
  '/visits/new': typeof AppVisitsNewRoute
  '/patients': typeof AppPatientsIndexRoute
  '/visits/$visitId/triage': typeof AppVisitsVisitIdTriageRoute
  '/visits/$visitId': typeof AppVisitsVisitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/patients/new': typeof AppPatientsNewRoute
  '/_app/visits/new': typeof AppVisitsNewRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/visits/$visitId/triage': typeof AppVisitsVisitIdTriageRoute
  '/_app/visits/$visitId/': typeof AppVisitsVisitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/patients/$patientId'
    | '/patients/new'
    | '/visits/new'
    | '/patients/'
    | '/visits/$visitId/triage'
    | '/visits/$visitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/patients/$patientId'
    | '/patients/new'
    | '/visits/new'
    | '/patients'
    | '/visits/$visitId/triage'
    | '/visits/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/patients/$patientId'
    | '/_app/patients/new'
    | '/_app/visits/new'
    | '/_app/patients/'
    | '/_app/visits/$visitId/triage'
    | '/_app/visits/$visitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits/new': {
      id: '/_app/visits/new'
      path: '/visits/new'
      fullPath: '/visits/new'
      preLoaderRoute: typeof AppVisitsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/new': {
      id: '/_app/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof AppPatientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits/$visitId/': {
      id: '/_app/visits/$visitId/'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId/'
      preLoaderRoute: typeof AppVisitsVisitIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits/$visitId/triage': {
      id: '/_app/visits/$visitId/triage'
      path: '/visits/$visitId/triage'
      fullPath: '/visits/$visitId/triage'
      preLoaderRoute: typeof AppVisitsVisitIdTriageRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppPatientsNewRoute: typeof AppPatientsNewRoute
  AppVisitsNewRoute: typeof AppVisitsNewRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppVisitsVisitIdTriageRoute: typeof AppVisitsVisitIdTriageRoute
  AppVisitsVisitIdIndexRoute: typeof AppVisitsVisitIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppPatientsNewRoute: AppPatientsNewRoute,
  AppVisitsNewRoute: AppVisitsNewRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppVisitsVisitIdTriageRoute: AppVisitsVisitIdTriageRoute,
  AppVisitsVisitIdIndexRoute: AppVisitsVisitIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
